name: tab_news
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.12
  mockito: ^5.1.0
  faker: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/
